#include <string.h>
#include <stdio.h>
int ft_printf(char const *str, ...);
int main(void)
{
  ft_printf("\n");
  printf("\n");
  printf("__________________________________\n");
  ft_printf("%%\n");
  printf("%%\n");
  printf("__________________________________\n");
  ft_printf("%d\n", 42);
  printf("%d\n", 42);
  printf("__________________________________\n");
  ft_printf("%d%d\n", 42, 41);
  printf("%d%d\n", 42, 41);
  printf("__________________________________\n");
  ft_printf("%d%d%d\n", 42, 43, 44);
  printf("%d%d%d\n", 42, 43, 44);
  printf("__________________________________\n");
  ft_printf("%ld\n", 2147483647);
  printf("%ld\n", 2147483647);
  printf("__________________________________\n");
  ft_printf("%lld\n", 9223372036854775807);
  printf("%lld\n", 9223372036854775807);
  printf("__________________________________\n");
  ft_printf("%x\n", 505);
  printf("%x\n", 505);
  printf("__________________________________\n");
  ft_printf("%X\n", 505);
  printf("%X\n", 505);
  printf("__________________________________\n");
  ft_printf("%p\n", &ft_printf);
  printf("%p\n", &ft_printf);
  printf("__________________________________\n");
  ft_printf("%20.15d\n", 54321);
  printf("%20.15d\n", 54321);
  printf("__________________________________\n");
  ft_printf("%-10d\n", 3);
  printf("%-10d\n", 3);
  printf("__________________________________\n");
  ft_printf("% d\n", 3);
  printf("% d\n", 3);
  printf("__________________________________\n");
  ft_printf("%+d\n", 3);
  printf("%+d\n", 3);
  printf("__________________________________\n");
  ft_printf("%010d\n", 1);
  printf("%010d\n", 1);
  printf("__________________________________\n");
  ft_printf("%hhd\n", 0);
  printf("%hhd\n", 0);
  printf("__________________________________\n");
  ft_printf("%jd\n", 9223372036854775807);
  printf("%jd\n", 9223372036854775807);
  printf("__________________________________\n");
  ft_printf("%zd\n", 4294967295);
  printf("%zd\n", 4294967295);
  printf("__________________________________\n");
  ft_printf("%\n");
  printf("%\n");
  printf("__________________________________\n");
  ft_printf("%U\n", 4294967295);
  printf("%U\n", 4294967295);
  printf("__________________________________\n");
  ft_printf("%u\n", 4294967295);
  printf("%u\n", 4294967295);
  printf("__________________________________\n");
  ft_printf("%o\n", 40);
  printf("%o\n", 40);
  printf("__________________________________\n");
  ft_printf("%%#08x\n", 42);
  printf("%%#08x\n", 42);
  printf("__________________________________\n");
  ft_printf("%x\n", 1000);
  printf("%x\n", 1000);
  printf("__________________________________\n");
  ft_printf("%#X\n", 1000);
  printf("%#X\n", 1000);
  printf("__________________________________\n");
  ft_printf("1 %s\n", NULL);
  printf("1 %s\n", NULL);
  printf("__________________________________\n");
  ft_printf("%S\n", L"ݗݜशব");
  printf("%S\n", L"ݗݜशব");
  printf("__________________________________\n");
  ft_printf("%s%s\n", "test", "test");
  printf("%s%s\n", "test", "test");
  printf("__________________________________\n");
  ft_printf("%s%s%s\n", "test", "test", "test");
  printf("%s%s%s\n", "test", "test", "test");
  printf("__________________________________\n");
  ft_printf("%C\n", 15000);
  printf("%C\n", 15000);
  printf("__________________________________\n");
  system("leaks a.out");
  return (0);
}
